---
version: '2'

services:
  database:
    image: postgres:12
    container_name: database
    environment:
      - TZ=Europe/London
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7Ie7jgcHARYLPQaG
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3

  horizon:
    build:
        context: /home/AzureUser/opennms-horizon/com617/Docker Compose/horizon/
        dockerfile: dockerfile
    container_name: horizon
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7Ie7jgcHARYLPQaG
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=j9h0P4UnaPPOE0Z5
    volumes:
      - ./share-opennms:/opt/opennms/share/rrd
      - ./overlay:/opt/opennms-overlay
      - ./etc-opennms:/opt/opennms/etc
    command: ["-s"]
    ports:
      - "8980:8980/tcp"
      - "8101:8101/tcp"
      - "61616:61616/tcp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3
    links:
      - grafana

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./data-grafana:/var/lib/grafana
    #ports:
    #  - "3000:3000/tcp"
    network_mode: host    
#networks:
    #  default:
    #      mode
